var romList=
{
	"Academy 2019":[
		"Blox_by Whitehat",
		"Castle Defender_by Jumpman",
		"Castle vs Castle_by Hydrochous",
		"Daisy Land_by Princess Daisy",
		"Dino Runner_by Hoid",
		"Donkey Kong_by Lionpride",
		"Dont fall_by Mr. Chomp",
		"Fencing Simulator_by Alberich",
		"Hole-Run_Speedy G.",
		"Moon Shot_by SchellLabs",
		"Pirates_by G. Freeman",
		"Space Defender_by KusoTech",
		"Unknown_by M4K5",
		"Vec Man_by Master Control",
		"Vec Man_parajve_by Master Control",
		"Vec Man_parajve_rc24_by Master Control",
		"Vec Man_rc24_by Master Control",
		"Vectroid_by NATE__66"
	],
	"Academy 2018":[
		"Asteroid Cowboy_by A.B.",
		"Asteroids_by L.D.",
		"Floor is lava_by Volcanus",
		"Floor is lava_vector_war_v2_by Volcanus",
		"Keyboard Hero_by W.L.",
		"Portal Fight_by J3W3L5",
		"Pyoro-Chan_by Swagger",
		"Split Personality_by M.S.",
		"Thirsty Astronaut_by Firemedic",
		"Treasure Diver_by Falrahch",
		"Yarg!_by Germanke",
		"Yarg! (no Overlay)_by Germanke"
		],
	"Academy 2017":[
		"Block Bomb_by Marvin Berstecher",
		"Curling_by Manuel Rettig",
		"Doodle Jump_by Robin Schelling",
		"Eating Fish_by KiriCreamCheese",
		"Hover Race_by Simeon Schüller",
		"Kingdom Of Heaven_by Jan David Kurfiß",
		"Knight Rider_by Blondie",
		"Lost Souls_by Gunterson",
		"Pac Men_by Manuel Debic",
		"Pipe Race_by Ralph Gerath",
		"Shark Attack_by by Maximilian Kellner",
		"Space Ball_by Tim Stiesch",
		"Space Patrol_by Andreas Barth",
		"Spaceship Centauri_by Christoph Bechtle",
		"Star Fuel_by Andreas Bauer",
		"Star War_by Marco Schewa"
	],
	"Academy 2016":[
		"Absorbtex_by Ana Bressel",
		"Artillery Strike_by Jan Langer",
		"Bacteria_by Matthias Bach",
		"BaseLoot_by Jan Hoffmann",
		"Blox Breaker_by Matthias Tiran",
		"Brick Crusher_by Tugce Ünsal, Ersin Dogan",
		"Headless Runner_by Timo Barth",
		"Hextrex_by Michael Tiran",
		"Hungry Python_by Maximilian Schiller",
		"Hurdles_by Marcel Krause",
		"Laser Wars_by Florian Krause",
		"Last Battle_by Jonas Krause",
		"Robhop_by Miss_Lissi",
		"Space Assault_by Fabian Pfeifroth",
		"Space Attack_by Abdalla Ifen",
		"Spikes_by Emanuel Blindow",
		"The Snake_by Matthias Schneider"
	],
	"Commercial":[
		"Armor Attack",
		"Bedlam",
		"Berzerk",
		"Blitz",
		"Clean Sweep",
		"Clean Sweep_(Mr Boston Version)",
		"Cosmic Chasm",
		"Fortress of Narzod",
		"Heads Up",
		"Hyperchase",
		"Mine Storm",
		"Mine Storm_II",
		"Polar Rescue",
		"Pole Position",
		"Rip-Off",
		"Scramble",
		"Solar Quest",
		"Space Wars",
		"Spike",
		"Spinball",
		"Star Castle",
		"Star Hawk",
		"Star Trek",
		"Web Wars"
	],
	"Unreleased":[
		"Dark Tower",
		"Mail Plane",
		"Pitchers Duel",
		"Test Rev. 4",
		"Tour De France"
	],
	"Hacks":[
		"2-D Narrow Escape_(by Fred Taft) (1983) [h1]",
		"Armor Attack_(Spinner Hack)",
		"Armor Attack_(Spinner Hack) [a1]",
		"Bedlam_(Spinner Hack)",
		"Berzerk_(Bugfixed Prototype)",
		"Dark Tower_(Fred Taft Hack)",
		"Mine Storm_(Karrsoft Hack) [h1]",
		"Mine Storm_(RLB Hack) [h1]",
		"Mine Storm_ II (1983) (Spinner Hack)",
		"Mine Storm_II(Fred Taft Hack) [h1]",
		"Polar Rescue_[a1]",
		"Pole Position_(Spinner Hack)",
		"Pole Position_[f1]",
		"Rip-Off_[b1]",
		"Solar Quest_(Spinner Hack)",
		"Star Castle_(Spinner Hack)",
		"Star Trek_- The Motion Picture (controller hack) [h1]",
		"Star Trek_- The Motion Picture[a1]",
		"Web Wars_[b1]"
	],
	"Homebrew":[
		"4-D Rotating Cube Demo (19xx)",
		"Abyss Demo (1999)",
		"Alpha Demo (2001)",
		"Arsek by Marq (2000)",
		"BCor-FTS Demo by Clay Cowgill (1997)",
		"Battle Earth Terror Hazard & Vecsports Boxing (2000)",
		"CGM Example by Marq (2000)",
		"Curved Lines Demo (1998)",
		"Disc Duel Demo (1997)",
		"Dual Vectrex Test #1 (1983)",
		"Dual Vectrex Test #2 (1983)",
		"Engine Analyzer (1983) (light pen)",
		"Exec Rom Dumper (2000) (Ronen Habot)",
		"Line Demo (2001)",
		"Lines and Digitized Sounds Demo (1998)",
		"Lunar Lander Demo by Thomas Landspurg (19xx)",
		"Mike's Molecules Demo by Mike Blackwell (1985)",
		"Mike's Molecules Demo by Mike Blackwell (1985) [a1]",
		"Moon Lander Demo by Clay Cowgill (1997)",
		"Moon Lander Demo by Clay Cowgill (1997) [a1]",
		"Music Demo (2001)",
		"Omega Chase (Final Version) (1998)",
		"Philly Classic 3 Demo (2002)",
		"Pythagorian Theorem by Rob Mitchell (2002)",
		"Revector by Craig Aker (2004)",
		"Rocket Sledge Demo (1985)",
		"Ronen's Game Cart (2000) (Ronen Habot)",
		"Rounders by Ronen Habot (2000)",
		"Sound1 Demo (19xx)",
		"Spectrum I+ Demo (1982)",
		"Spike Goes Skiing (1998)",
		"Spike Goes Skiing Demo V.03 (1998)",
		"Spike's Slam Pit Demo by Gauze (2001)",
		"Tank Demo 1 (19xx)",
		"Tank Demo 2 (2001)",
		"Text Demo (2001)",
		"This is Just a Non-Playable Demo (1999)",
		"Thrust",
		"Tono Demo by Marq & Antti (2000)",
		"Vaboom! by Ronen Habot (2000) [a1]",
		"Vaboom! by Ronen Habot (2000)",
		"VecVoice Demo by Richard Hutchinson (2002)",
		"Vecmania Part 1 (1999) [a1]",
		"Vecmania Part 1 (1999)",
		"Vecmania Part 2 (1999)",
		"Vectrace (2000) (Ronen Habot) [a1]",
		"Vectrace (2000) (Ronen Habot) [a2]",
		"Vectrace (2000) (Ronen Habot)",
		"Vectrex BIOS (1982)",
		"Vectrex Pong (1998)",
		"Vectrexians (1999)",
		"Verzerk by Alex Herbert (2002)",
		"War of the Robots by George Pelonis (2003)",
		"ZZAP - Scrolling Space Game Demo (1989)"
	],
	"Chris Salomon":[
		"Vector Blade_(2019)",
		"'NO' Sound (1998)",
		"Arkanoid - Revenge of DOH Sound (1998)",
		"Axel F - Beverly Hills Cop (1998) ",
		"Axel F - Beverly Hills Cop (1998) [a1]",
		"Bebop Best Sound (1998)",
		"Bebop Sound (1998)",
		"Bubble Bobble (Diamond Room) (1998)",
		"Bubble Bobble Sound 0 (1998)",
		"Bubble Bobble Sound 1 (1998)",
		"Bubble Bobble Sound 2 (1998)",
		"Bubble Bobble Sound 2best (1998)",
		"Bubble Bobble Sound 3 (1998)",
		"Commando - High Score Sound (1998)",
		"Count05 Sound (1998)",
		"Dr. Who Theme (1998)",
		"Fast Food Sound 1 (1998)",
		"Fast Food Sound 2 (1998)",
		"Ghosts 'n' Goblins Sound 7 (1998)",
		"Ghosts 'n' Goblins Sound 8 (1998)",
		"Ghosts 'n' Goblins Sound 9 (1998)",
		"Ghosts 'n' Goblins Sound 9best (1998)",
		"Ghouls 'n' Ghosts Sound (1998)",
		"Great Giana Sisters (Bonus) (1998)",
		"Great Giana Sisters (Ingame) (1998)",
		"Great Giana Sisters (Title) (1998)",
		"Hey, Music Lover Sound (1998)",
		"Jaws Theme Music (1998)",
		"Klax (Level Begin) Sound (1998)",
		"Labyrinth Rev 1 (1998)",
		"Labyrinth Rev 2 (1998)",
		"Labyrinth Rev 3 (1998)",
		"Labyrinth Rev 4 (Vector Rouge) (1998)",
		"Madonna's Get Into the Groove (1998)",
		"Misfits 1 Music (1998)",
		"Monty on the Run HiScore Sound (1998)",
		"Monty on the Run Sound (1998)",
		"Monty on the Run Sound (1998) [a1]",
		"Pac-Mania Sound 1 (1998)",
		"Pac-Mania Sound 2 (1998)",
		"Pac-Mania Sound 4 (1998)",
		"Rainbow Islands Sound (1998)",
		"Real Ghostbusters Sound (1998)",
		"Robin Hood Sound (1998)",
		"Star Wars Sound (1998)",
		"Star Wars Theme (1998)",
		"Turrican 1 Sound (1998)",
		"Turrican 2 Sound (1998)",
		"V-Frogger (1998)",
		"V-Frogger (1998) [a1]",
		"V-Frogger Sound by Kurt Woloch (2001)",
		"Vectrex Maze (1998)",
		"YM001 Sound (1998)",
		"Zombies from the Crypt Music (1998)"
	],
	"Jeff Woolsey":[
		"Bach Prelude #1 (1985)",
		"Etch-a-Sketch (1985) (light pen)",
		"My Bonnie Lies Over The Ocean (1985)",
		"Star Spangles Banner Music Demo (1985)",
		"Vectrex Bootstrap Loader (1985)",
		"We Wish You a Merry Christmas (1985)",
		"We Wish You a Merry Christmas (1985) [a1]",
		"We Wish You a Merry Christmas (1986)"
	],
	"Christopher Tumber":[
		"3-D Demo (Mar 06) (2000)",
		"3-D Demo (Mar 08) (2000)",
		"3-D Scrolling Demo (2001)",
		"8Ball (2001)",
		"Battlezone Demo (2001)",
		"Calibration Demo (19xx)",
		"Missile Lords (2001)",
		"Omega Chase (2000)",
		"POP Demo (19xx)",
		"SAW Gallery 1 (1999)",
		"SAW Gallery 2 (1999)",
		"SAW Gallery 3 (1999)",
		"Song Demo (1998)",
		"Tsunami (2001)",
		"Tsunami (2001) [a1]",
		"Tsunami (2001) [a2]",
		"Version Nine (1999)",
		"Version Nine (1999) [a1]",
		"Version Nine (2000)"
	],
	"John Dondzila":[
		"All Good Things (1996)",
		"Birds of Prey (1999)",
		"Gravitrex (2002)",
		"Mad Planetoids Demo (2001)",
		"Patriots III - BALListics Busters (1996)",
		"Patriots III - BALListics Busters (2002)",
		"Patriots Remix (1999)",
		"Patriots (1996)",
		"Patriots (1996) [a1]",
		"Repulse (1999)",
		"Rockaroids Remix - 3rd Rock (1996)",
		"Rockaroids Remix - 3rd Rock (1996) [a1]",
		"Space Frenzy",
		"Spike Hoppin' (1998)",
		"Spike's Water Balloons (Analog) (2001)",
		"Star Fire Spirits (1999) [a1]",
		"Star Fire Spirits (1999)",
		"Star Seige (1999)",
		"Vectopia (2001)",
		"Vector Vaders Remix (1999)",
		"Vector Vaders (1996)",
		"Vector Vaders (1996) [a1]",
		"Wormhole (2001)"
	],
	"Manu":[
		"0ldsk00l Demo (2002)",
		"All Your Base Demo (2001)",
		"Animation Demo (2002)",
		"BB2 Demo (2002)",
		"Battle Earth Terror Hazard V1 (2000)",
		"Battle Earth Terror Hazard V2 (2000)",
		"Battle Earth Terror Hazard V3 (2000)",
		"Battle Earth Terror Hazard V4 (2000)",
		"Collision Test (2000)",
		"Joystick Demo (2000)",
		"Nona3 (Mar 10) (2003)",
		"Pokemon Demo 1 (2000)",
		"Pokemon Demo 2 (2000)",
		"Pokemon Demo 3 and Marq (2000)",
		"Pokemon Demo 4 - Psyduck's Eyes (2000)",
		"ROM Music Demo (2000)",
		"Rotation Demo (2000)",
		"Scorefont 3 (Aug 26) (2002)",
		"Space16 Demo (2000)",
		"Taulukko Demo (2002)",
		"VecSports Kingpin Bowling Demo (Aug 19) (2002)",
		"VecSports Kingpin Bowling (V0.2) (2002)",
		"VecSports Kingpin Bowling (V0.3) (2002)",
		"VecSports Kingpin Bowling (V0.4) (Aug 26) (2002)",
		"Vecsports Boxing Demo (2000)",
		"Vecsports Boxing With Sound Demo (2000)",
		"Vectrex Demo 1 (2000)",
		"Vectrex Demo 2 (2000)",
		"Vectrex Demo 3 (2000)",
		"Vexperience - B.E.T.H. & Vecsports Boxing (2000)",
		"Vimpula (2002)"
	],
	"Lightpen":[
		"AnimAction",
		"Art Master",
		"Melody Master"
	],
	"3DImager":[
		"3-D Crazy Coaster",
		"3-D Mine Storm",
		"3-D Narrow Escape"
	]
}
